### ISSUE TITLE
Bucket utility behaviour if bucket size is less than 1

### ISSUE THREAD

**Issue by jleft** [d3fc/d3fc-sample#31]
I'm not sure if this is something which should be handled, as having a bucket size < 1 is illogical (I _think_!).

**Current behaviour**

```js
bukcet().bucketSize(0.5)([0, 1]);
//=> [ [  ], [ 0 ], [  ], [ 1 ] ]
```

**Proposed behaviour**

If the bucket size specified is less than 1 , then the number of buckets returned should equal the length of the data (i.e. the effective bucket size would be 1):

```js
bukcet().bucketSize(0.5)([0, 1]);
//=> [ [ 0 ], [ 1 ] ]
```

I think this is fairly consistent with the behaviour when a large bucket size is specified (ensuring the actual bucket size is <= data.length):

```js
bukcet().bucketSize(100)([0, 1]);
//=> [ [ 0 , 1 ] ]
```

**Comment by ColinEberhardt** [comment]
Your proposed behaviour makes sense to me.
