### ISSUE TITLE
largestTriangleThreeBucket() - does not support array accessors

### ISSUE THREAD

**Issue by envision** [d3fc/d3fc-sample#35]
I'm debugging an error, do you have idea what this might be about?

This dataset has 873100 datapoints and bucketSize is set to 1147.

    TypeError: Cannot read property '0' of undefined
        at https://project.dev/pkg/d3fc-sample/d3fc-sample-3.0.3.js:156:42
        at Array.map (native)
        at largestTriangleThreeBucket (https://project.dev/pkg/d3fc-sample/d3fc-sample-3.0.3.js:137:42)
        at Object.draw (https://project.dev/chart/sensordata.js:57:46)
        at https://project.dev/sensordataCtrl.js:31:36
        at https://project.dev/pkg/angular/js/angular-1.4.11.min.js:121:20
        at n.$eval (https://project.dev/pkg/angular/js/angular-1.4.11.min.js:135:219)
        at n.$digest (https://project.dev/pkg/angular/js/angular-1.4.11.min.js:132:306)
        at n.$apply (https://project.dev/pkg/angular/js/angular-1.4.11.min.js:135:513)
        at g (https://project.dev/pkg/angular/js/angular-1.4.11.min.js:88:374)

**Comment by envision** [comment]
It seems I had some inconsistencies / empty values in this dataset.

**Comment by envision** [comment]
Got it working! The problem was in that when I had data as an array of array of values and access them like:

	var sampler = fc.largestTriangleThreeBucket()
		.x(function(item) { return item[0]; })
	        .y(function(item) { return item[1]; });

I needed to change my data formatting to an array of objects:

	var sampler = fc.largestTriangleThreeBucket()
		.x(function(d) { return d.t; })
	        .y(function(d) { return d.v; });

But having 4 million datapoints as objects with named params doesn't seem ideal memory wise as compared to an array of value arrays?

So it seems this _largestTriangleThreeBucket_ method doesn't handle data data in array format.

**Comment by ColinEberhardt** [comment]
Yes, you're right - this is a bug. Here is a complete example that reproduces the issue:

```
var randomData = fc.randomGeometricBrownianMotion().steps(100);
var data = randomData(20).map(function(d, i) { return [i, d]; });

var sampler = fc.largestTriangleThreeBucket()
	.x(function(item) { return item[0]; })
  .y(function(item) { return item[1]; })
  .bucketSize(10);

var sampledData = sampler(data);

console.log(sampledData);
```

**Comment by ColinEberhardt** [comment]
@WPFerg would you be interested in looking into this? :-)

**Comment by WPFerg** [comment]
@ColinEberhardt No problem, pull request is up
