### ISSUE TITLE
Area of triangle formula makes no sense

### ISSUE THREAD

**Issue by didiersmith** [d3fc/d3fc-sample#44]
This formula blows my mind:
```
var base = (lastPoint[0] - nextPoint[0]) * (thisPoint[1] - lastPoint[1]);
var height = (lastPoint[0] - thisPoint[0]) * (nextPoint[1] - lastPoint[1]);
return Math.abs(0.5 * base * height);
```

Obviously it's some version of 1/2 base * height, but I've never seen this method of calculating base and height before. It looks like base and height are rectangular areas (you're multiplying x and y distances after all) and thus multiplying them together would yield a 4-dimensional shape. How this ends up returning the area of the triangle is totally beyond me! I also found this formula in the referenced thesis, but without explanation.

It seems like this would return 0 if nextPoint and lastPoint have the same y-value.  (nextPoint[1] - lastPoint[1]) would be 0, and following the multiplication through would make the whole formula return 0. That doesn't seem right.

I would have expected this code to use a well-known formula. Does this formula have a name? It would be good if you left a comment about it in the code, I'm sure I'm not the only confused person.

Here's a quick python example of this formula operating on a triangle with base 10 and height 5, along with an implementation of Heron's formula. This formula returns 0, Heron's correctly returns 25.

As this formula is the fundamental core of the algorithms here, I'm sure you guys have it correct but I can't for the life of me figure out how to use it. What am I missing here?

```
import math

def weirdArea(lastPoint, thisPoint, nextPoint):
   base = (lastPoint[0] - nextPoint[0]) * (thisPoint[1] - lastPoint[1]);
   height = (lastPoint[0] - thisPoint[0]) * (nextPoint[1] - lastPoint[1]);
   return abs(0.5 * base * height);

def heronArea(lastPoint, thisPoint, nextPoint):
  def lineLength(a, b):
    return math.sqrt(math.pow(a[0]-b[0], 2) + math.pow(a[1]-b[1],2))
  l1=lineLength(lastPoint, thisPoint)
  l2=lineLength(thisPoint, nextPoint)
  l3=lineLength(nextPoint, lastPoint)
  s=(l1+l2+l3)/2
  return math.sqrt(s*(s-l1)*(s-l2)*(s-l3))

t1 = ([0,0],[5,5],[10,0])
print weirdArea(t1[0], t1[1], t1[2]) # 0
print heronArea(t1[0], t1[1], t1[2]) # 25.0
```

**Comment by chrisprice** [comment]
This code was contributed by @WPFerg so he might be able to give a more detailed answer. In the meantime here's a [blog post](http://blog.scottlogic.com/2015/11/16/sampling-large-data-in-d3fc.html) he published around the same time which might contain the answer you're looking for.

**Comment by didiersmith** [comment]
Thanks, @chrisprice. I've read the blog post and it doesn't contain any information on the formula.

Looking at the thesis, its version of the formula is subtly different - instead of multiplying base and height together, the things that your code calls "base" and "height" are subtracted. Obviously they aren't actually the base and height! This actually yields the correct answer. The name of the formula is still a mystery to me but at least it isn't obviously incorrect.

I recommend you guys update your implementation!

```
import math

def thesisArea(lastPoint, thisPoint, nextPoint):
   return abs( ( lastPoint[0] - nextPoint[0] ) *(thisPoint[1] - lastPoint[1])
      - ( lastPoint[0] - thisPoint[0] ) * ( nextPoint[1] - lastPoint[1] ) ) * 0.5 

def weirdArea(lastPoint, thisPoint, nextPoint):
   base = (lastPoint[0] - nextPoint[0]) * (thisPoint[1] - lastPoint[1]);
   height = (lastPoint[0] - thisPoint[0]) * (nextPoint[1] - lastPoint[1]);
   return abs(0.5 * base * height);

def heronArea(lastPoint, thisPoint, nextPoint):
  def lineLength(a, b): 
    return math.sqrt(math.pow(a[0]-b[0], 2) + math.pow(a[1]-b[1],2))
  l1=lineLength(lastPoint, thisPoint)
  l2=lineLength(thisPoint, nextPoint)
  l3=lineLength(nextPoint, lastPoint)
  s=(l1+l2+l3)/2
  return math.sqrt(s*(s-l1)*(s-l2)*(s-l3))


t1 = ([0,0],[5,5],[10,0])
print weirdArea(t1[0], t1[1], t1[2])  # 0 
print thesisArea(t1[0], t1[1], t1[2]) # 25
print heronArea(t1[0], t1[1], t1[2])  # 25
```

**Comment by didiersmith** [comment]
FYI the formula is on the second-to-last page of https://skemman.is/bitstream/1946/15343/3/SS_MSthesis.pdf

**Comment by WPFerg** [comment]
Ah, apologies. I must have misunderstood what was going on in the formula/mistranslated it when renaming variables etc.

From a very quick glance it could be a factorised version of the [shoelace formula](https://en.wikipedia.org/wiki/Shoelace_formula#Proof_for_a_triangle)
